=== 641i130/Ayaka/bins/ayaka-gui/src/locale/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "LangResources",
    "description": "A resource file of translation",
    "type": "object",
    "properties": {
        "dialogYes": {
            "description": "The YES button in dialog",
            "type": "string"
        },
        "dialogNo": {
            "description": "The NO button in dialog",
            "type": "string"
        },
        "dialogOk": {
            "description": "The OK button in dialog",
            "type": "string"
        },
        "newGame": {
            "description": "The new game button at HomeView",
            "type": "string"
        },
        "loadRecords": {
            "description": "The load records button at HomeView",
            "type": "string"
        },
        "settings": {
            "description": "The settings button at HomeView, and title at SettingsView",
            "type": "string"
        },
        "language": {
            "description": "The language caption in the SettingsView",
            "type": "string"
        },
        "subLanguage": {
            "description": "The secondary language caption in the SettingsView",
            "type": "string"
        },
        "bgmVolume": {
            "description": "BGM volume caption in the SettingsView",
            "type": "string"
        },
        "voiceVolume": {
            "description": "Voice volume caption in the SettingsView",
            "type": "string"
        },
        "videoVolume": {
            "description": "Video volume caption in the SettingsView",
            "type": "string"
        },
        "none": {
            "description": "The choice none",
            "type": "string"
        },
        "about": {
            "description": "The about button at HomeView",
            "type": "string"
        },
        "goHome": {
            "description": "The go home button at GameView",
            "type": "string"
        },
        "goHomeConfirm": {
            "description": "The confirm message in go home confirm dialog",
            "type": "string"
        },
        "quit": {
            "description": "The quit button at HomeView",
            "type": "string"
        },
        "quitConfirm": {
            "description": "The confirm message in quit confirm dialog",
            "type": "string"
        },
        "error": {
            "description": "The error title of dialog",
            "type": "string"
        }
    },
    "required": []
}

=== 641i130/Ayaka/bins/ayaka-gui/src/locale/en.json
{
    "$schema": "./schema.json",
    "dialogYes": "Yes",
    "dialogNo": "No",
    "dialogOk": "OK",
    "newGame": "New game",
    "loadRecords": "Load records",
    "settings": "Settings",
    "language": "Language",
    "subLanguage": "Secondary language",
    "bgmVolume": "BGM volume: ",
    "voiceVolume": "Voice volume: ",
    "videoVolume": "Video volume: ",
    "none": "None",
    "about": "About",
    "goHome": "Go home",
    "goHomeConfirm": "Back to the home page?",
    "quit": "Quit",
    "quitConfirm": "Quit the game?",
    "error": "Error"
}

=== 641i130/Ayaka/bins/ayaka-gui/src/locale/zh_Hans.json
{
    "$schema": "./schema.json",
    "dialogYes": "是",
    "dialogNo": "否",
    "dialogOk": "确定",
    "newGame": "新游戏",
    "loadRecords": "加载进度",
    "settings": "设置",
    "language": "语言",
    "subLanguage": "第二语言",
    "bgmVolume": "背景音乐音量：",
    "voiceVolume": "语音音量：",
    "videoVolume": "视频音量：",
    "none": "无",
    "about": "关于",
    "goHome": "主页",
    "goHomeConfirm": "返回主页？",
    "quit": "退出",
    "quitConfirm": "退出游戏？",
    "error": "错误"
}

=== 641i130/Ayaka/bins/ayaka-gui/src/locale/ja.json
{
    "$schema": "./schema.json",
    "dialogYes": "はい",
    "dialogNo": "いいえ",
    "dialogOk": "OK",
    "newGame": "始めから",
    "loadRecords": "続きから",
    "settings": "設定",
    "language": "言語",
    "subLanguage": "第二言語",
    "none": "無し",
    "about": "説明",
    "goHome": "ホーム",
    "goHomeConfirm": "ホームに戻りますか？",
    "quit": "終了する",
    "quitConfirm": "ゲームを終了しますか？",
    "error": "エラー"
}

=== 641i130/Ayaka/bins/gal-gui/src/locale/ja.json
{
    "$schema": "./schema.json",
    "dialogYes": "はい",
    "dialogNo": "いいえ",
    "dialogOk": "OK",
    "newGame": "始めから",
    "loadRecords": "続きから",
    "settings": "設定",
    "about": "説明",
    "goHome": "ホーム",
    "goHomeConfirm": "ホームに戻りますか？",
    "quit": "終了する",
    "quitConfirm": "ゲームを終了しますか？",
    "error": "エラー"
}
